======================================================================
FAIL: test_get_future_imports (tests.test_black.BlackTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rowaha/work/llm-fl/BugsInPy/framework/bin/temp/black/tests/test_black.py", line 741, in test_get_future_imports
    self.assertEqual({"unicode_literals"}, black.get_future_imports(node))
  File "/home/rowaha/work/llm-fl/BugsInPy/framework/bin/temp/black/black.py", line 2937, in get_future_imports
    assert import_from_child.type == syms.import_as_names
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (failures=1)